<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.21" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETICARET.Business\ETICARET.Business.csproj" />
    <ProjectReference Include="..\ETICARET.DataAccess\ETICARET.DataAccess.csproj" />
    <ProjectReference Include="..\ETICARET.Entities\ETICARET.Entities.csproj" />
  </ItemGroup>

</Project>
